include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

  errors:
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_const_declarations: warning
    avoid_unnecessary_containers: warning
    sized_box_for_whitespace: warning
    use_colored_box: warning
    use_decorated_box: warning
    cancel_subscriptions: warning
    close_sinks: warning
    use_build_context_synchronously: warning

linter:
  rules:
    # Const لتحسين الأداء وتقليل إنشاء Objects جديدة
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # تقليل الـ Widgets والعمليات غير الضرورية
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
    unnecessary_lambdas: true

    # استخدام final عندما لا تتغير القيمة
    prefer_final_fields: true
    prefer_final_locals: true

    # منع تسريب الـ Streams والـ Subscriptions
    cancel_subscriptions: true
    close_sinks: true

    # أمان وجودة الكود
    use_build_context_synchronously: true
    discarded_futures: true
    avoid_print: true