import '../entities/driver_performance_chart_point_entity.dart';
import '../entities/driver_performance_entity.dart';
import '../entities/driver_performance_metric_card_entity.dart';

class DriverPerformanceFakeData {
  const DriverPerformanceFakeData._();

  static const DriverPerformanceEntity todayPerformance =
      DriverPerformanceEntity(
    formattedDate: 'السبت ، 24 مايو 2025',
    isOnline: true,
    totalOrders: 8,
    onTimeRate: '92%',
    deliveriesCount: 8,
    totalDistance: '32.4',
    onTimeCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceOnTimeRate',
      value: '92%',
      trendText: '8%',
      isAreaChart: true,
      isAmber: false,
      points: [
        DriverPerformanceChartPointEntity(label: '00:00', value: 82),
        DriverPerformanceChartPointEntity(label: '03:00', value: 76),
        DriverPerformanceChartPointEntity(label: '06:00', value: 88),
        DriverPerformanceChartPointEntity(label: '09:00', value: 85),
        DriverPerformanceChartPointEntity(label: '12:00', value: 95),
        DriverPerformanceChartPointEntity(label: '15:00', value: 80),
        DriverPerformanceChartPointEntity(label: '18:00', value: 84),
        DriverPerformanceChartPointEntity(label: '21:00', value: 75),
        DriverPerformanceChartPointEntity(label: '24:00', value: 65),
      ],
    ),
    deliveriesCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceDeliveries',
      subtitleKey: 'driverPerformanceHandover',
      value: '8',
      trendText: '2',
      isAreaChart: false,
      isAmber: false,
      points: [
        DriverPerformanceChartPointEntity(label: '00:00', value: 2),
        DriverPerformanceChartPointEntity(label: '02:00', value: 3),
        DriverPerformanceChartPointEntity(label: '04:00', value: 2),
        DriverPerformanceChartPointEntity(label: '06:00', value: 4),
        DriverPerformanceChartPointEntity(label: '08:00', value: 3),
        DriverPerformanceChartPointEntity(label: '10:00', value: 3),
        DriverPerformanceChartPointEntity(label: '12:00', value: 6),
        DriverPerformanceChartPointEntity(label: '14:00', value: 4),
        DriverPerformanceChartPointEntity(label: '16:00', value: 5),
        DriverPerformanceChartPointEntity(label: '18:00', value: 2),
        DriverPerformanceChartPointEntity(label: '20:00', value: 3),
        DriverPerformanceChartPointEntity(label: '22:00', value: 4),
        DriverPerformanceChartPointEntity(label: '24:00', value: 0),
      ],
    ),
    distanceCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceTotalDistance',
      value: '32.4كم',
      trendText: '0.9 كم',
      isAreaChart: true,
      isAmber: true,
      points: [
        DriverPerformanceChartPointEntity(label: '00:00', value: 28),
        DriverPerformanceChartPointEntity(label: '03:00', value: 24),
        DriverPerformanceChartPointEntity(label: '06:00', value: 26),
        DriverPerformanceChartPointEntity(label: '09:00', value: 32),
        DriverPerformanceChartPointEntity(label: '12:00', value: 22),
        DriverPerformanceChartPointEntity(label: '15:00', value: 21),
        DriverPerformanceChartPointEntity(label: '18:00', value: 24),
        DriverPerformanceChartPointEntity(label: '21:00', value: 23),
        DriverPerformanceChartPointEntity(label: '24:00', value: 16),
      ],
    ),
    workingHoursCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceWorkingHours',
      value: '5:45',
      trendText: '0:45',
      isAreaChart: false,
      isAmber: true,
      points: [
        DriverPerformanceChartPointEntity(label: '00:00', value: 2),
        DriverPerformanceChartPointEntity(label: '02:00', value: 3),
        DriverPerformanceChartPointEntity(label: '04:00', value: 2),
        DriverPerformanceChartPointEntity(label: '06:00', value: 3),
        DriverPerformanceChartPointEntity(label: '08:00', value: 3),
        DriverPerformanceChartPointEntity(label: '10:00', value: 3),
        DriverPerformanceChartPointEntity(label: '12:00', value: 5),
        DriverPerformanceChartPointEntity(label: '14:00', value: 3),
        DriverPerformanceChartPointEntity(label: '16:00', value: 4),
        DriverPerformanceChartPointEntity(label: '18:00', value: 2),
        DriverPerformanceChartPointEntity(label: '20:00', value: 3),
        DriverPerformanceChartPointEntity(label: '22:00', value: 4),
        DriverPerformanceChartPointEntity(label: '24:00', value: 0),
      ],
    ),
  );

  static const DriverPerformanceEntity thisWeekPerformance =
      DriverPerformanceEntity(
    formattedDate: 'الأسبوع 21 ، مايو 2025',
    isOnline: true,
    totalOrders: 48,
    onTimeRate: '95%',
    deliveriesCount: 46,
    totalDistance: '210.5',
    onTimeCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceOnTimeRate',
      value: '95%',
      trendText: '4%',
      isAreaChart: true,
      isAmber: false,
      points: [
        DriverPerformanceChartPointEntity(label: 'السبت', value: 90),
        DriverPerformanceChartPointEntity(label: 'الأحد', value: 92),
        DriverPerformanceChartPointEntity(label: 'الاثنين', value: 89),
        DriverPerformanceChartPointEntity(label: 'الثلاثاء', value: 94),
        DriverPerformanceChartPointEntity(label: 'الأربعاء', value: 96),
        DriverPerformanceChartPointEntity(label: 'الخميس', value: 95),
        DriverPerformanceChartPointEntity(label: 'الجمعة', value: 98),
      ],
    ),
    deliveriesCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceDeliveries',
      subtitleKey: 'driverPerformanceHandover',
      value: '46',
      trendText: '6',
      isAreaChart: false,
      isAmber: false,
      points: [
        DriverPerformanceChartPointEntity(label: 'السبت', value: 7),
        DriverPerformanceChartPointEntity(label: 'الأحد', value: 6),
        DriverPerformanceChartPointEntity(label: 'الاثنين', value: 8),
        DriverPerformanceChartPointEntity(label: 'الثلاثاء', value: 6),
        DriverPerformanceChartPointEntity(label: 'الأربعاء', value: 7),
        DriverPerformanceChartPointEntity(label: 'الخميس', value: 8),
        DriverPerformanceChartPointEntity(label: 'الجمعة', value: 4),
      ],
    ),
    distanceCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceTotalDistance',
      value: '210.5كم',
      trendText: '18 كم',
      isAreaChart: true,
      isAmber: true,
      points: [
        DriverPerformanceChartPointEntity(label: 'السبت', value: 30),
        DriverPerformanceChartPointEntity(label: 'الأحد', value: 28),
        DriverPerformanceChartPointEntity(label: 'الاثنين', value: 34),
        DriverPerformanceChartPointEntity(label: 'الثلاثاء', value: 29),
        DriverPerformanceChartPointEntity(label: 'الأربعاء', value: 32),
        DriverPerformanceChartPointEntity(label: 'الخميس', value: 36),
        DriverPerformanceChartPointEntity(label: 'الجمعة', value: 21),
      ],
    ),
    workingHoursCard: DriverPerformanceMetricCardEntity(
      titleKey: 'driverPerformanceWorkingHours',
      value: '38:30',
      trendText: '3:15',
      isAreaChart: false,
      isAmber: true,
      points: [
        DriverPerformanceChartPointEntity(label: 'السبت', value: 6),
        DriverPerformanceChartPointEntity(label: 'الأحد', value: 5.5),
        DriverPerformanceChartPointEntity(label: 'الاثنين', value: 6),
        DriverPerformanceChartPointEntity(label: 'الثلاثاء', value: 5),
        DriverPerformanceChartPointEntity(label: 'الأربعاء', value: 6),
        DriverPerformanceChartPointEntity(label: 'الخميس', value: 6),
        DriverPerformanceChartPointEntity(label: 'الجمعة', value: 4),
      ],
    ),
  );
}
